#!/bin/bash

lineNum=1
file=$1
arg=$2

function usage () {
#display usage of program
        printf "\n./lineNum ['filename'] ['-n'] -- -n is optional\n"
        printf "Filename chooses what file to display\n"
        printf "'-n' Allows the file to be printed with line numbers\n\n"
        exit 0
}

if [[ "$file" == '' ]]; then
#If no argument provided exit program
        printf "No file provided\n\n"
        exit 1;
elif [[ "$file" == '-h' ]]; then
#If -h argument provided display usage
        usage
fi


function print_linenums() {
#While there is a line to read in the file keep looping
#Add the line num before the line and print it, increment the line num for each line
while read -r line; do
	printf "$lineNum. $line\n"
	((lineNum++))
done < $file
}

function print_file() {
	while read -r line; do
		printf "$line\n"
	done < $file
}

if [[ ! -z $arg ]] && [[ $arg == '-n' ]]; then
#If a second argument is provided and the argument is -n dispaly the file with line numbers
        print_linenums
elif [[ ! -z $arg ]] && [[ $arg != '-f' ]]; then
#If a second argument is provided but it is not == to -n show usage and exit prgoram
        usage
else
	print_file
fi
